	title	Rigid Partition Disk Parameter Blocks

	.z80

;;	Copyright (C) 1981 Balcones Computer Corporation.
;

;;	Rigid Partition Disk Parameter Blocks.
;
;	There are 16 4k Blocks per pseudo track.
;	Track Zero (2 Cylinders) are reserved for CP/M boot.
;
Nt4	equ	64		;Number of Tracks on Partition 0
Nt5	equ	32		;Number of Tracks on Partition 1
Nt6	equ	16		;Number of Tracks on Partition 2
Nt7	equ	16		;Number of Tracks on Partition 3

..	aset	0		;First usable track

	irpc	n,<4567>
..	aset	..+1		;reserve system track
Dsm&n	equ	Nt&n*16-17
Rtk&n	equ	..
..	aset	..+Nt&n-1
Dpbrg&n::dw	512		;spt
	db	5,31		;blkshf, blkmsk
	db	3+2*(Dsm&n ge 256);exm
	dw	Dsm&n		;dsm
	dw	511		;dirmax
	db	-1		;alloc0 (reserve additional dir space)
	db	0		;alloc1
	dw	0		;check size
	dw	Rtk&n		;track offset
	db	1		;256 byte sectors
	endm

	end
