	title	Western Digital WD-1797-02 Floppy Disk Driver		

	.z80

;;	Western Digital WD-1797-02 Floppy Disk Driver.
;
;	Copyright (c) 1981, Balcones Computer Corporation
;
;;	Standard Disk Driver Interface Definitions.
;
;	The main entry point (FLOPPY) is called with HL pointing
;	to a disk driver request block.  All information is passed
;	in this request as follows:
;
;	HL->	db	command	;1 = read, 0 = write, -1 = select dph
;		db	phunit	;physical unit for request (0-3)
;		db	cpunit	;CP/M logical drive for request (0-15)
;		dw	track	;CP/M track number (offset already applied)
;		dw	sector	;Phys sector number (after deblocking)
;		dw	address	;CP/M dma transfer address
;
;	The standard deblocker processes CP/M BIOS style select
;	requests.  If the selected drive is not logged in, the
;	deblocker issues a driver Select command.  The deblocker
;	remembers the address of the DPH returned by the driver in
;	order to quickly process successive BIOS select calls to a
;	drive that is already logged in, by returning this address
;	without assistance from the physical driver.
;
;	The Select command causes the media to be examined for its
;	density and drive type.  This information is maintained locally
;	by the driver for use in following read/write requests.  The
;	driver then returns the address of a CP/M disk parameter header
;	in register HL that coresponds to the unit and media format.
;	The media may not be changed without issuing another driver
;	Select command.  Note that a driver MUST NOT remember the unit
;	for later use since this Select command is issued only once
;	when the disk is logged in.  The Select command request block
;	will contain only the first three bytes. (-1, phunit, cpunit)
;
;	The Read and Write commands process physical sectors according
;	to the density determined by the previously issued Select command.
;	The request block contains the unit, track, sector, and transfer
;	address.  For double density diskettes, the transfer address will
;	point to one of the deblocker's host buffers, and 256 bytes must
;	be transfered to/from there.  However, for single density diskettes
;	the transfer address will point directly to the users dma buffer,
;	but only 128 bytes may be transfered.
	subttl	Assembly Constants
	page	60
;;	Monitor Entry Points.
;
daytim	equ	0f039h		;get address of timer data
idle	equ	0f066h		;idle cpu
soft	equ	0f069h		;record soft error

NMI	equ	00066h		;address of non maskable interrupt

;;	WD 1797 I/O port addresses.
;
wdsr	equ	10h		;status
wdcr	equ	10h		;command
wdtr	equ	11h		;track
wdsn	equ	12h		;sector
wddt	equ	13h		;data

wdsl	equ	1ch		;drive select port
wdsd	equ	30h		;select single density
wddd	equ	31h		;select double density


;;	External Disk Parameter Tables.
;
	extrn	Dpbase,Dpb8s,Trn6

fm.un	equ	7
fm.ds	equ	4
fm.dd	equ	5
fm.fv	equ	6
fm.ddss	equ	(1 shl fm.dd) or (1 shl fm.un)

ntrk8	equ	77
ntrk5	equ	40

c.8in	equ	4
c.two	equ	5
timout	equ	6		;motor / select time out
dpbofs	equ	10		;offset in dph for dpb address

	subttì	Floppù Disë Driveò Proper
	page
;;	Western Digital Floppy Disk Driver.
;
Dskdvr::call	rdc		;un hang busy controller
	ld	a,(hl)		;set command
	inc	hl		;point to unit
	ld	(rdop),a
	inc	a
	jr	z,select	;if select command
	ld	b,10		;set retry count
flop1:	push	bc		;save count
	push	hl		;save command
	ld	a,(hl)		;set unit select
	call	selunt
	jp	m,flop5		;if unit not ready
	inc	hl
	inc	hl
	ld	c,(hl)		;set track low
	call	seek		;position disk
	ld	c,(hl)		;retrieve track low
	jr	nz,flop5	;if unrecoverable error
	inc	hl		;track high
	inc	hl
	inc	de		;point to second byte of track table entry
	ld	a,(de)		;get diskette type
	and	18h
	ld	a,(hl)		;sector low
	jr	nz,flop2	;if single density, cp/m skews
	ld	a,c		;get current logical track
	or	a
	ld	a,(hl)		;set sector
	jr	z,flop2		;if single density track zero
	inc	a		;translate for double density
flop2:	out	(wdsn),a	;set sector to read in 1791
	inc	hl		;skip sector high
	inc	hl		;dmal
	ld	e,(hl)		;set transfer address to HL
	inc	hl		;dmah
	ld	d,(hl)
	ex	de,hl
	ld	a,0		;set read/write switch
rdop	equ	$-1
	or	a
	ld	c,0a8h		;preset write command
	ld	a,0a3h		;set second part of OUTI
	jr	z,flop3		;if write
	ld	c,088h		;turn write command into read command
	dec	a		;turn OUTI into INI
flop3:	ld	(rdwra),a	;set up i/o direction
	ld	a,0
rdwrs	equ	$-1		;set side compare flag
	add	a,c
	ld	c,a
	call	stc		;start transfer
flop4:	halt			;wait for DRQ or INT
		ini		;transfer next byte
rdwra	equ	$-1
	jr	nz,flop4	;if transfer not complete
	call	ttc		;terminate transfer command
	and	0dfh		;set error bits
flop5:	pop	hl		;recover command pointer
	pop	bc
	ret	z		;if no errors
	ret	c		;if 5.25" not ready
	call	soft
	djnz	flop1		;if retry not exceeded
	ret

;;	select - select dph for unit.
;
select:	ld	a,(hl)		;set unit
	cp	4
	jp	nc,selerr##	;if bad unit select
	ld	h,0
	call	daytim		;set address of timers
	dec	hl		;point to motor timer
	ld	(mtradr),hl
	dec	hl		;point to configurable step rate
	ld	(stpadr),hl	;store address of step rate for media selector
	ld	h,0
	ld	l,a
	add	hl,hl		;multiply by 2**4
	add	hl,hl
	add	hl,hl
	add	hl,hl
	ld	de,Dpbase	;set address of disk parameter headers
	add	hl,de		;set dph address
	push	hl
	call	smf		;set media format
	pop	hl
	jp	z,selerr##	;if no media
	ld	(hl),c		;store translate table
	inc	hl
	ld	(hl),b
	ld	bc,dpbofs
	add	hl,bc		;point to dpb addr and clear carry
	ld	(hl),d		;fill in dpb address
	dec	hl
	ld	(hl),e
	sbc	hl,bc		;point back to dph
	xor	a
	ret

;;	select physical unit.
;
selunt:	ld	c,a		;save select
	ex	de,hl
	ld	hl,trktbl+1	;set track / density table address
	ld	b,0
	add	hl,bc
	add	hl,bc
	ld	(smfa),hl	;save address for media selector
	ex	de,hl
	ld	a,(de)		;get previous density switch
	dec	de		;point to track word
	call	selden		;select density
	ld	a,timout	;start motor / select timer
	ld	(mtradr),a
mtradr	equ	$-2		;address filled in by once only routine
	ei			;insure clock enabled
	res	1,c		;map C->A, D->B
	in	a,(wdsl)	;read current select
	ld	b,a
	and	not 7
	or	c		;insert new select
	inc	a		;0-1, 1-2
	out	(wdsl),a	;select drive
	xor	b
	and	3
	jr	z,sel3		;if drive select identical
	ld	a,-1		;force track position recovery
	ld	(de),a
	bit	c.8in,b		;test 8/5 status
	jr	nz,sel3		;if 8"
	call	rdc		;set type I status
	ld	b,2*4		;watch for four holes (8 transitions)
sel1:	push	hl
	ld	hl,(mtradr)	;get address of motor select timer
	ld	a,(hl)
	pop	hl
	sub	timout-2	;look for 1-2 seconds
	ret	c		;if drive not spinning
	in	a,(wdsr)
	and	2
sel2:	jr	z,sel1		;if index not under light
	ld	a,(sel2)	;switch index polarity
	xor	8 ; (jr z) xor (jr nz)
	ld	(sel2),a
	djnz	sel1		;wait for at least three revolutions
sel3:	in	a,(wdsr)	;set ready status
	and	80h
	ret

seldns:	ld	a,18h		;set track zero single density
selden:	ld	(dsw),a		;store switch for read/write routines
	and	18h
	out	(wddd),a	;pre-select dual density
	ret	z		;if dual density
	out	(wdsd),a	;select single density
	ret

;;	seek - position disk.
;
seek:	ld	a,c		;set new track
	or	a
	call	z,seldns	;force single density track 0
	inc	de
	ld	a,(de)
	dec	de
	and	1
	jr	z,sek1		;if one sided diskette
	in	a,(wdsl)
	bit	c.8in,a
	ld	b,ntrk8		;set number of eight inch tracks
	jr	nz,sek0		;if 8" drives
	ld	b,ntrk5
sek0:	ld	a,c		;set seek track
	cp	b
	ld	a,0		;preset side 0
	jr	c,sek1		;if side 0
	ld	a,c
	sub	b		;wrap to side 1
	ld	c,a
	ld	a,2		;set side 1
sek1:	ld	(rdwrs),a	;store F1 (update SS0)
	add	a,a		;move into select port position
	ld	b,a
	di
	in	a,(wdsl)
	res	2,a
	or	b
	ei
	out	(wdsl),a	;send out REAL SS0
	ld	a,(de)		;check current position
	out	(wdtr),a	;inform 1797 of current track
	cp	c
	jr	z,seek3		;if position ok, load head
	inc	a		;check for forced recovery
	call	z,rse		;recover seek errors
	jr	z,seek1		;if error not recoverable
seek0:	ld	a,c		;set new track
	out	(wddt),a	;in data register
	ld	a,1ch		;set seek with verify command
	call	isc		;issue step command
	and	98h
	ld	a,c		;update current track
	jr	z,seek2		;if no errors
seek1:	or	-1		;force recovery next time
seek2:	ld	(de),a
	ret
seek3:	call	rdc		;set type I status
	and	20h		;test head load
	jr	z,seek0		;if head is not loaded
retzr:	xor	a		;say seek complete
	ret

;;	rse - recover seek error.
;
rse:	push	bc
	call	rdid		;read id mark
	jr	nz,rse1		;if track position identified
	call	recal		;recalibrate
	and	4		;verify track zero flag set
rse1:	pop	bc
	ret

;;	rdid - read id mark.
;
rdid:	ld	c,0c4h		;set Read Address Command
	call	stc		;start transfer command
	halt			;wait for interrupt
	in	b,(c)		;first byte is track
	halt
	in	c,(c)		;second byte is side, pitch next 4
	call	ttc		;terminate transfer command
	and	98h		;ignore lost data
	jr	nz,rdid1	;if track not identified
	ld	a,b
	out	(wdtr),a	;tell 1797 track head is on now
	defb	0f6h		;or xra to set NZ
rdid1:	xor	a		;set track not found
	ret

;;	stc - start transfer command.
;
stc:	di			;lock normal interrupts
	ld	a,(NMI)		;save byte at NMI address
	ld	(ttca),a
	ld	a,0c9h		;store RET there
	ld	(NMI),a
	ld	a,c		;retrieve command
	ld	bc,wddt+20*256	;1797 access timer / data port
	out	(wdcr),a	;issue command
	djnz	$		;pause 60 usec
	ld	a,0
dsw	equ	$-1		;density switch
	and	18h		;say ready and density
	ret	z		;if double density
	ld	b,128		;set 128 byte single density sectors
	ret

;;	ttc - terminate transfer command.
;
ttc:	ld	a,0		;restore location 66
ttca	equ	$-1
	ld	(NMI),a
	ei			;take interrupts now
	jr	woc		;wait for 1797 to complete

;;	recalibrate drive.
;
recal:	xor	a		;set restore command / track 0
	ld	(de),a		;set track zero

;;	isc - issue step command.
;
isc:	or	1		;insert step rate
stepr	equ	$-1	;*****=>;modify here for step rate change
	jr	icc

rdc:	ld	a,0d0h		;terminate and set type I status

;;	icc  - issue controller command.
;
icc:	out	(wdcr),a	;issue 1797 command

;;	woc  - wait operation complete.
;
woc:	ld	a,20		;set 60 usec delay
woc1:	dec	a
	jr	nz,woc1
woc2:	call	idle		;idle cpu
	in	a,(wdsr)	;set 1797 status
	bit	0,a
	jr	nz,woc2		;if busy, wait
	ret

	subttl	Media Format Selector
	page

;;	smf - set media format.
;
;	entry:	unit in A
;
;	exit:	DE = dpb address
;		BC = translate table
;
smf:	call	selunt		;select unit
	jp	m,retzr		;if disk not ready
	ld	hl,dtype
	ld	(hl),fm.ddss	;start out double density, single side, retry
	in	a,(wdsl)	;read select status
	bit	c.8in,a		;test 8" / 5" status
	jr	nz,smf0		;if 8 inch drives
	set	fm.fv,(hl)	;move up to 5.25" dpbs
smf0:	ld	a,(stpadr)	;set configurable step rate for 8" drives
stpadr	equ	$-2
	and	3		;just so seeks aren't formats
	ld	(stepr),a	;save step rate in seek command
smf0a:	call	recal		;establish position
	and	84h
	ret	z		;if not on track zero
	jp	m,retzr		;if unit not ready
	out	(wddd),a	;set double density
	ld	a,-1
	ld	(de),a		;clear drive on track
	ld	a,2		;use track 2 for density select
	out	(wddt),a
	ld	a,18h		;seek / no verify
	call	isc		;issue seek command
	ld	a,1ch		;find id mark
	out	(wdcr),a	;start verify
	ld	bc,0		;set timers
smf1:	djnz	$		;pause
	in	a,(wdsr)
	bit	0,a
	jr	z,smf1a		;if command completed
	dec	c
	jr	nz,smf1		;if more time
	call	rdc		;terminate seek
	ld	a,18h		;set pseudo record not found
smf1a:	and	18h		;check record not found / crc error
	inc	de		;point to density word in track table
	ld	(de),a
	dec	de
	jr	z,smf2		;if density select successful
	out	(wdsd),a	;use single density
	ld	a,1ch		;verify single density
	call	isc		;issue seek
	and	18h
	jr	z,smf1b		;if single density successful
	bit	fm.un,(hl)	;test retry
	res	fm.un,(hl)	;clear retry
	jr	nz,smf0a	;if retry
	ret			;return select error
smf1b:	res	fm.dd,(hl)	;back up to single density dpbs
smf2:	res	fm.un,(hl)	;clear retry
	in	a,(wdsl)
	set	2,a		;select side 2
	out	(wdsl),a
	call	rdid		;read id mark
	jr	z,smf4		;if no id found, must be one side
	dec	c
	jr	nz,smf4		;if side 1 ID not read
	set	fm.ds,(hl)	;bump up to two sided dpbs
	ld	hl,smfa		;set double sided status in track table
smfa	equ	$-2
	inc	(hl)
smf4:	ld	hl,0		;set diskette type
dtype	equ	$-2
	ld	a,l		;save type
	ld	c,h		;preset no translate
	ld	b,h
	ld	de,dpb8s	;set base of disk parameter blocks
	add	hl,de
	ex	de,hl		;return DPB address in DE
	bit	fm.dd,a
	ret	nz		;if diskette is double density
	ld	bc,trn5		;preset 5.25" skew table
	bit	fm.fv,a
	ret	nz		;if diskette is small
	ld	bc,trn6		;set 8" translate
	inc	a		;force NZ
	ret

;;	Skew by 5 translate table.
;
trn5::	db	01,06,11,16
	db	03,08,13,18
	db	05,10,15,02
	db	07,12,17,04
	db	09,14

trktbl:

	end
