€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€

	if	optrom
	ld	hl,version
	ld	a,(hl)
	cp	'0'
	ret	nz
	inc	(hl)		;advance version number
err1:
err2:
	ret

	ds	800h-€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€;

Rx1984:	call	patch		;patch floppy driver in ram
	or	-1		;say disk driver not initialized yet
	ret
	else
start:
	endif	equ	0f094h
patch1	equ	0f4c9h		;push bc
patch2	equ	0f4cdh		;pop  bc
patch3	equ	0f651h		;call idle
patch4	equ	0f652h
patch5	ееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееее€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€3-$+Rx1984,-1
	dw	55aah		;magic Rx1984 number
	db	0		;check sum goes here
	.dephase

move:	ldir
	ret
	else
	ld	de,msg1
€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€

patch:	ld	a,(patch1-1)	;fetch ld c,(hl)
	sub	4eh
	jr	nz,err1		;if not WD rom driver
	ld	a,(patch1)
	or	a
	jr	z,err2		;ifequ	0f653h

	aseg
	org	100h

	if	optrom

start:	ld	hl,code
	ld	bc,800h-1
	call	ccs
	neg
	ld	(hl),a
	ld	hl,code
	ld	ееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееее€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€	jr	sprint
err1:	ld	de,msg2
	jr	print
err2:	ld	de,msg3
sprint:	ld	a,(5dh)
	cp	' '
	jp	nz,0		;if silence requested
print:	